### ISSUE TITLE
The card has ux/ui bug in Live train status section.

### ISSUE THREAD

**Issue by Anandshukla987** [ratan2020cs131/Puchtach-Express#1]
![image](https://github.com/ratan2020cs131/Puchtach-Express/assets/84628402/7a638d96-7175-4b9b-b2ed-ce6856d333fc)
The time of arriving and departing overflows from the parent container.

How to reproduce this error:-
1. go to live train status 
2. search train
3. you can see the error

**Comment by ratan2020cs131** [comment]
Thanks @Anandshukla987 for your contribution
